name: Docker Build and Push

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Compose (ensure your docker-compose.yml is in the repo)
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          # This will use your docker-compose.yml to build both frontend and backend
          file: docker-compose.yml

      # Build and push images using Docker Compose
      - name: Build and push Docker images
        run: |
          docker compose version
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push
